return newsletter support
nephila/aldryn-jobs pull request #1
Opened 2020-04-03 13:08 UTC by Amanit

2020-04-05 11:27 UTC, yakky requested changes

2020-04-05 11:27 UTC, yakky commented on aldryn_jobs/urls.py
> +    url(r'^confirm-newsletter/$',
Newsletter urls must go on top, otherwise url pattern from `CategoryJobOpeningList` and `JobOpeningDetail` will match instead

2020-04-06 07:24 UTC, Amanit commented on aldryn_jobs/urls.py
> +    url(r'^confirm-newsletter/$',
ty, fixed

2020-04-06 07:42 UTC, yakky approved these changes

2020-04-06 07:42 UTC, merged